### ISSUE TITLE
Make UI Components

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Sinatra-Sequel-Backbone#6]
## Tasks:

- [ ] **Create UI components based on Bootstrap Material Design:**

Components:

- [ ] - Button -> _btn_concept.scss
- [ ] - Button Floating -> _btn_floating.scss
- [ ] - Card -> _card.scss
- [ ] - Collection -> _collection.scss
- [ ] - Comment Form -> _comment_form.scss
- [ ] - Input  -> _input.scss
- [ ] - Modal  -> _modal.scss
- [ ] - Navbar -> _navbar.scss
- [ ] - Proyect Preview -> _proyect_preview.scss
- [ ] - Snippet Preview -> _snippet_preview.scss
- [ ] - Tag Input -> Input.scss

------------------

- [ ] **Bridge main.scss, there are styles of UI components that should be in their respective file, such as input ta, btn floating, and collections**

-------------------

- [ ] **Make a _settings.scss file to save colors and config variables**
